# percentage of the test set in split dataset
test_size: 0.3
# path to store results images
result_path: "images/results"
features:
  # list of quantitative features
  quant1: ['Churn', 'Customer_Age', 'Dependent_count', 'Months_on_book',
           'Total_Relationship_Count', 'Months_Inactive_12_mon',
           'Contacts_Count_12_mon']
  quant2: ['Credit_Limit', 'Total_Revolving_Bal', 'Avg_Open_To_Buy',
           'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt', 'Total_Trans_Ct',
           'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio']
  # list of categorical columns
  categorical: ['Gender', 'Education_Level', 'Marital_Status',
                'Income_Category', 'Card_Category']
  # list of features used in model training
  keep: ['Customer_Age', 'Dependent_count', 'Months_on_book',
         'Total_Relationship_Count', 'Months_Inactive_12_mon',
         'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
         'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
         'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
         'Gender_Churn', 'Education_Level_Churn', 'Marital_Status_Churn',
         'Income_Category_Churn', 'Card_Category_Churn']
# parameters for GridSearchCV
grid_params:
  n_estimators: [200, 500]
  max_features: ['auto', 'sqrt']
  max_depth: [4, 5, 100]
  criterion: ['gini', 'entropy']
